### ISSUE TITLE
Unable to patch it with st-ligatures 

### ISSUE THREAD

**Issue by prateekshukla1108** [sergei-grechanik/st-graphics#2]
I can't figure out which of the patches will work

**Comment by sergei-grechanik** [comment]
Try this branch (or cherry-pick the head commit): https://github.com/sergei-grechanik/st-graphics/tree/graphics-with-ligatures
There were quite a few conflicts, mostly straightforward, but most importantly I had to slightly modify the hbtransform function in hb.c:
```c
	/* Fill buffer with codepoints. */
	for (rune_idx = 0, glyph_idx = start; glyph_idx < end; glyph_idx++, rune_idx++) {
		hbrunebuffer.runes[rune_idx] = glyphs[glyph_idx].u;
		mode = glyphs[glyph_idx].mode;
		if (mode & ATTR_WDUMMY)
			hbrunebuffer.runes[rune_idx] = 0x0020;
		/* Draw spaces for image placeholders. */
		if (mode & ATTR_IMAGE)
			hbrunebuffer.runes[rune_idx] = 0x0020;
	}
```
Both ligatures and images seem to work, but I haven't tested it extensively.

**Comment by sergei-grechanik** [comment]
Fixed a couple of bugs and mentioned the patch in the readme, closing as done.

**Comment by prateekshukla1108** [comment]
great
I think that adding features like font2 boxdraw scrollback geometry and xresources will make it very much usable and better than most of the terminals
