### ISSUE TITLE
Would you mind making it a patch?

### ISSUE THREAD

**Issue by Alce-tar-gz** [sergei-grechanik/st-graphics#3]
Why'd you make a fork when it could've been a patch?

**Comment by sergei-grechanik** [comment]
I'll try to submit it to suckless.org, although it's admittedly a little too big for a patch. Here is the diff against the current master with some redundant stuff excluded: [st-kitty-graphics-20240922-a0274bc.diff.txt](https://github.com/user-attachments/files/17107236/st-kitty-graphics-20240922-a0274bc.diff.txt)

**Comment by sergei-grechanik** [comment]
Done: https://st.suckless.org/patches/kitty-graphics-protocol/
